<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="map" tilewidth="16" tileheight="16" tilecount="132" columns="12" objectalignment="center" tilerendersize="grid" fillmode="preserve-aspect-fit">
 <transformations hflip="0" vflip="0" rotate="1" preferuntransformed="0"/>
 <image source="tilemap_packed.png" trans="000000" width="192" height="176"/>
 <tile id="0" type="Floor"/>
 <tile id="1" type="Wall"/>
 <tile id="2" type="Wall"/>
 <tile id="3" type="Wall"/>
 <tile id="4" type="Wall"/>
 <tile id="5" type="Wall"/>
 <tile id="6" type="Wall"/>
 <tile id="7" type="Fountain"/>
 <tile id="8" type="Fountain"/>
 <tile id="9" type="Door"/>
 <tile id="10" type="Door"/>
 <tile id="11" type="Door"/>
 <tile id="12" type="Floor"/>
 <tile id="13" type="Wall"/>
 <tile id="14" type="Wall"/>
 <tile id="15" type="Wall"/>
 <tile id="16" type="Wall"/>
 <tile id="17" type="Wall"/>
 <tile id="18" type="Wall"/>
 <tile id="19" type="Fountain"/>
 <tile id="20" type="Fountain"/>
 <tile id="21" type="Door"/>
 <tile id="22" type="Door"/>
 <tile id="23" type="Door"/>
 <tile id="24" type="Floor"/>
 <tile id="25" type="Wall"/>
 <tile id="26" type="Wall"/>
 <tile id="27" type="Wall"/>
 <tile id="28" type="Wall"/>
 <tile id="29" type="Wall"/>
 <tile id="30" type="Wall"/>
 <tile id="31" type="Fountain"/>
 <tile id="32" type="Fountain"/>
 <tile id="33" type="Door"/>
 <tile id="34" type="Door"/>
 <tile id="35" type="Door"/>
 <tile id="36" type="Wall"/>
 <tile id="37" type="Wall"/>
 <tile id="38" type="Wall"/>
 <tile id="39" type="Wall"/>
 <tile id="40" type="Wall"/>
 <tile id="41" type="Wall"/>
 <tile id="42" type="Floor"/>
 <tile id="43" type="Fountain"/>
 <tile id="44" type="Fountain"/>
 <tile id="45" type="Door"/>
 <tile id="46" type="Door"/>
 <tile id="47" type="Door"/>
 <tile id="48" type="Floor"/>
 <tile id="49" type="Floor"/>
 <tile id="50" type="Floor"/>
 <tile id="51" type="Floor"/>
 <tile id="52" type="Floor"/>
 <tile id="53" type="Floor"/>
 <tile id="54" type="Cart"/>
 <tile id="55" type="Cart"/>
 <tile id="56" type="Cart"/>
 <tile id="57" type="Wall"/>
 <tile id="58" type="Wall"/>
 <tile id="59" type="Wall"/>
 <tile id="63" type="Crate"/>
 <tile id="64" type="Tombstone"/>
 <tile id="65" type="Tombstone"/>
 <tile id="66" type="Grave"/>
 <tile id="67" type="Track"/>
 <tile id="68" type="Track"/>
 <tile id="69" type="Track"/>
 <tile id="70" type="Track"/>
 <tile id="71" type="Track"/>
 <tile id="79" type="Track"/>
 <tile id="80" type="Track"/>
 <tile id="81" type="Track"/>
 <tile id="82" type="Barel"/>
 <tile id="83" type="Track"/>
 <tile id="87" type="Viking"/>
 <tile id="89" type="Chest"/>
 <tile id="90" type="Chest"/>
 <tile id="91" type="Chest"/>
 <tile id="92" type="Chest"/>
 <tile id="93" type="Track"/>
 <tile id="94" type="Track"/>
 <tile id="95" type="Track"/>
 <tile id="99" type="Princess"/>
</tileset>
